spring.application.name=projetolds

springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

api.security.admin.default-username=${ADMIN_USER}
api.security.admin.default-password=${ADMIN_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.properties.hibernate.format_sql=true